spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password: Kavindu@dilshan

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl